name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type to bump: patch, minor, or major'
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bumpversion

    - name: Run bumpversion
      run: |
        bumpversion ${{ github.event.inputs.version }}  # Bump the version
