name: Release Version

on:
  push:
    branches: [ "main" ]

jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: npx semantic-release